### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by halokaya67** [code-dot-org/code-dot-org#20553]
I want to help this project by translating it into turkish. I'm turkish and 25 years old. I'm working as an english teacher in a school. I think i can help. Please just show me which file should i translate and you will see. You won't regret because i take my job serious.

**Comment by tanyaparker** [comment]
@halokaya67 thank you for your interest in helping us with translations. We do our translations through Crowdin and [you can start immediately here](https://crowdin.com/project/codeorg/tr#). For more information about our translation process, please visit [code.org/translate](code.org/translate). If you have any further questions, please email translations@code.org instead of opening a GitHub issue. Thanks!
