### ISSUE TITLE
rake install then got stuck

### ISSUE THREAD

**Issue by kkkisme** [code-dot-org/code-dot-org#21686]
```bash
dev@iZ2zec6ll6nvbh4acez5unZ:~/code-dot-org/dashboard$ bundle exec rake db:drop
Dropped database 'dashboard_development'
Dropped database 'dashboard_test'
dev@iZ2zec6ll6nvbh4acez5unZ:~/code-dot-org/dashboard$ cd ../
dev@iZ2zec6ll6nvbh4acez5unZ:~/code-dot-org$ ls
apps  codecov.yml      dashboard      experimental  i18n     locals.yml          NOTICE    README.md  STYLEGUIDE.md  Vagrantfile
aws   CONTRIBUTING.md  deployment.rb  Gemfile       lib      locals.yml.default  pegasus   SETUP.md   TESTING.md
bin   cookbooks        docs           Gemfile.lock  LICENSE  log                 Rakefile  shared     tools
dev@iZ2zec6ll6nvbh4acez5unZ:~/code-dot-org$ rake install
bundle --without production adhoc staging test levelbuilder integration --quiet --jobs 4
mysql://root@localhost/dashboard_development
RAILS_ENV=development RACK_ENV=development bundle exec rake dashboard:setup_db
```

stucked at this step about 30mins(ssh connection will be abort)，do i have any wrong opration?

**Comment by tanyaparker** [comment]
@kkkisme thank you for reporting! We have an engineer on our team experiencing the same issue and she is currently debugging/investigating a resolution. We'll update you soon when we know more.

**Comment by epeach** [comment]
@kkkisme Hi! These commands look correct. I was experiencing these issues and, unfortunately, I wasn't able to identify an individual cause or resolution as I was trying a lot of things to get it resolved. What I think might have helped the most was checking that I had the correct versions of the dependencies as listed in our [setup documentation](https://github.com/code-dot-org/code-dot-org/blob/staging/SETUP.md), as well as, rake 11.3.0, which was the rake version a co-worker was successfully using. 

After setting those versions, I was able to run `rake install` successfully. It took between 90 minutes and and 2 hours to completely seed the database. I was able to monitor the process by running `mysql dashboard_development -u root <<< "SELECT COUNT(0) FROM levels;"` in another terminal. There are approximately 11,000 levels, which are seeded as part of the install process, and I was able to watch the number of levels grow throughout the process of `rake install`.

Because running `rake install` may take a while, you might need to find a way to prevent ssh disconnection. I recommend looking into the `screen` command, which keeps a session running when it's disconnected.

We appreciate feedback on our set-up process. Please let us know if you experience any other trouble!

**Comment by kkkisme** [comment]
@epeach thanks a lot,i will try it

**Comment by eduardobcastro** [comment]
Here it took about 2 hours to finish
