### ISSUE TITLE
ActiveRecord::RecordNotFound in CoursesController#index

### ISSUE THREAD

**Issue by kris-cote** [code-dot-org/code-dot-org#41150]
return script if script

    raise ActiveRecord::RecordNotFound.new("Couldn't find Script with id|name=#{id_or_name}")
  end

  # Returns the script with the specified id, or a script with the specified

What is causing this?

**Comment by truongson-devgame** [comment]
I also have the same problem. Please help

**Comment by evilcrash** [comment]
`ActiveRecord::RecordNotFound` in your context is raised in [script.rb](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/models/script.rb) and is probably an issue with Rails' schema. I'm no expert on Ruby on Rails, but my assumption would be that for whatever reason, `id_or_name` is resulting in that error. Because there's no exception handler, `id_or_name` instead of equaling nil is just crashing the whole thing.

I know something changed in Rails 4 with `find_by`. Could you provide the output of `rails -v` and `mysql -V`? Ruby's version should be 2.5, Rails should be 5.2, and I believe you should have MySQL 5.7.
