### ISSUE TITLE
Add Table Name button doesn't work

### ISSUE THREAD

**Issue by snickell** [code-dot-org/code-dot-org#56460]
Broken:
![Image](https://github.com/code-dot-org/code-dot-org/assets/223277/157e8792-1bd2-4fea-bd79-584385c1e1fa)

Might be the table add button might be using the Table schema, but the list is doing the old/haffbaked Records style.

**Comment by puneethkumarvh** [comment]
Hi @snickell ,I am finding difficulty while setting up the project and getting the below error. Can you please help me set up the project so I can start working on fixing the bug?
![image](https://github.com/code-dot-org/code-dot-org/assets/69886724/e4914cd5-f0e1-4682-ac62-11124dc0c509)
I'm sure there are no syntax errors as it say. I think it is causing because of configurations. Are there any dummy credentials to start with?

**Comment by snickell** [comment]
Hi @puneethkumarvh , I _believe_ this issue is actually fixed (but we didn't mark it correctly).

That said, if you are interested in contributing, I'd be happy to help with your build, could you upload your config.yml.erb? Even knowing what is at line 631 could help, even if there is no syntax issue.
