### ISSUE TITLE
Implement cron-updating tables (daily weather, spotify, etc)

### ISSUE THREAD

**Issue by cnbrenci** [code-dot-org/code-dot-org#56993]
In Datablock Storage, unlike in the firebase version, we don't distinguish between "shared_tables" and "current_tables". Shared tables are just a pointer to the real dataset, which is stored in the DatablockStorageTable table with a project_id of 0.

There are 3 "current tables", which are a result of 3 different cron jobs running (from `bin/cron/applab_datasets`), fetching data, and updating tables.

**Comment by snickell** [comment]
All 3x cron jobs just use `fb.upload_live_table(table_name, records, columns)`, which:
1.  Deletes the shared table
2. Updates the shared table's data
3. Sets the lastUpdated timestamp on the shared table.

**Comment by snickell** [comment]
OMG, so the covid19 data source appears to be not updating, and additionally, is storing the Date field WITHOUT A YEAR (current table / table in firebase has this problem too):
```
{"id": 8, "Date": "Sat 12/24", "State": "Connecticut", "Total Deaths": 11733, "Total Confirmed Cases": 943284}
```

The [raw data source](https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv) includes a year, but the covid19 script goes out of its way to remove the year from the data:
```
    parsed_date = Date.strptime(line.field("date"), "%Y-%m-%d")
    formatted_date = parsed_date.strftime('%a %-m/%-d') # ex Wed 1/7
    record['Date'] = formatted_date
```

**Comment by snickell** [comment]
Yeah, the raw data source for covid19, https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv, stops at `2023-03-23`

@kakiha11 I've done the work to port the script that runs nightly and updates the "`'COVID-19 Cases per US State'` table, but.... the [NYTimes git repo](https://github.com/nytimes/covid-19-data) we're using as a data source stopped updating their data in March of 2023:
![Image](https://github.com/user-attachments/assets/0e971800-4c0b-4445-aca7-eddafbd573fe)

I believe we should:
1. Delete the covid19 script, since its specific to this data source, and fixing this script that broke over a year ago is out of scope for the Firebase => Datablock Storage migration.
2. Delete the 'COVID-19 Cases per US State' table from the manifest, **unless** we reference it somewhere in curriculum.
3. Keep the 'COVID-19 Cases per US State' table in the database, just not included in the manifest. This will mean projects that reference this table won't be broken, but you can't add the table to any new projects (it won't show up in the data browser).

Thoughts? Alternative ideas?
